### ISSUE TITLE
Status code 206 from listdevices breaks the UI

### ISSUE THREAD

**Issue by slaupster** [ibm-messaging/iot-visualization#2]
For some reason the error callback is driven when the response to /api/v0001/organization/getdevices is 206 in uicontroller.js.  My reading of the jquery docs suggest that it should drive success so I'm confused.  However, if 206 is received from the API then we don't get any devices in the UI.

The best fix here is probably to move to V2 APIs.

**Comment by jeffdare** [comment]
Hi,

Yes, its better to move to V2 APIs now.. Will make the changes and post here.

**Comment by jeffdare** [comment]
This is fixed in https://github.com/ibm-messaging/iot-visualization/commit/23ad0988dcbd8e2d63d2576fd23353b2b5ca5d6a.
Closing issue.
